### ISSUE TITLE
Remove Learning Gatsby Section

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#10]
- Simply remove the learning Gatsby section. 
- Add a simple header for the future **Contributors** section. 

  - For Hacktoberfest and new people to OSS contribution please provide a detailed commit message and Pull Request. I will review thoroughly.

**Comment by zbeach** [comment]
I'd like to do this!

**Comment by JacobMGEvans** [comment]
Have at it :)

**Comment by abhishekr700** [comment]
Hi, Is this still open ?

**Comment by JacobMGEvans** [comment]
@abhishekr700 No but you can check out issue #23 which is also a documentation issue you can work on.
