### ISSUE TITLE
Transfer to an Organization 

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#20]
- name suggestions for organization

**Comment by blindingstars** [comment]
Looks good! I added circle-friendly logos in #22 that could work for the org icon :)

**Comment by JacobMGEvans** [comment]
@blindingstars for you and anyone else you know that is interested. 
Slack Channel invitation, expires in 7 days 
https://join.slack.com/t/lakecountytechmeetup/shared_invite/enQtNzkzNTI5NzE3ODg4LTg2NGE2MGUyYWYzNzMwNmFlMTdkNmI5MmNhNjM4ZGU0ZGU3ZDQ2ZjM2YzM0N2M2ODQzZWMxZTA0NDdmOTAzY2M

**Comment by JacobMGEvans** [comment]
Closing #20
