### ISSUE TITLE
Setting up infrastructure for Testing

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#26]
- Jest & React testing library are the main tools 
  - RTL install docs can be found here: https://testing-library.com/docs/react-testing-library/intro

Setting up codebase for testing can be found in Gatsby docs here:  https://www.gatsbyjs.org/docs/unit-testing/

**Comment by benfluleck** [comment]
Can I work on this 🙏 ?

**Comment by JacobMGEvans** [comment]
Go for it, start off with a `/__tests__ ` at the root of the repository. 

- Be sure to follow the Gatsby directions.
- If you can configure  https://testing-library.com/docs/react-testing-library/intro to work with Gatsby all the better. 
- Also, Testing-Library has this https://github.com/testing-library/react-hooks-testing-library, however, getting that configured for this Pull Request is optional

**Comment by benfluleck** [comment]
https://github.com/lake-county-tech-meetup/website/pull/29
