### ISSUE TITLE
Prettier & ESlint configurations

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#30]
**Describe the bug**
There is an issue where some of the Prettier and ESlint configurations are conflicting. 

**Expected behavior**
Prettier and ESlint should be working together and have no conflicts

**Screenshots**
None available currently, will get some next time.

**Comment by benfluleck** [comment]
Can I take this

**Comment by benfluleck** [comment]
Do you have a list of config you would like to use for this project?

**Comment by JacobMGEvans** [comment]
> Do you have a list of config you would like to use for this project?

There is already an `.eslintrc ` file in the project.  [Found Here](https://github.com/lake-county-tech-meetup/website/blob/master/.eslintrc)

This was an issue with the configuration issue as in, the setup like packages and settings ect...

which was possibly resolved with PR #31

**Comment by JacobMGEvans** [comment]
@benfluleck If you want to go through and make sure you don't run into Prettier and ESLint conflicts meaning on save the Prettier and ESlint doesn't cause formatting or linting fixes to be added then immediately reverted back and still throw a linter error then that would be helpful.

If you continue to see that problem feel free to try and fix it and add those changes to a PR :)
