### ISSUE TITLE
CONTRBUTING.md 

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#33]
- The file needs to be created and tailored this project
- Be sure to adhere to best practices and industry standards for this type of document. 
- Use other major OSS projects CONTRIBUTING.md as a reference as needed.

**Comment by HeartBeat1608** [comment]
@JacobMGEvans I could do this.

**Comment by JacobMGEvans** [comment]
Sounds good. Go ahead ill assign you later.

**Comment by HeartBeat1608** [comment]
@JacobMGEvans Opened the Pull Request. Used available terms from the repo.
