### ISSUE TITLE
Contact Us Page 

### ISSUE THREAD

**Issue by JacobMGEvans** [lake-county-tech-meetup/website#5]
- The Contact Us page will need a form
- The form should have user contact info inputs i.e. email, phone number
- A message field 

The design and layout can be minimalist/sparse for now the page can later be built upon.

**Comment by JacobMGEvans** [comment]
Keep in mind I plan on implementing Netlify form handling. 
https://www.netlify.com/docs/form-handling/

If you can implement this, great. If not, then getting things started is equally great.

**Comment by bhagatparwinder** [comment]
I'll do it

**Comment by bhagatparwinder** [comment]
https://github.com/JacobMGEvans/lake-county-tech-meetup/pull/8

**Comment by coraman** [comment]
@bhagatparwinder is this issue still open?

**Comment by JacobMGEvans** [comment]
> @bhagatparwinder is this issue still open?

If you want to add some basic styling to the form by utilizing tailwind that is installed then I would say go for it.
